apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/esarath/ArgoCD-Basics-To-Production.git
  password: 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
  username: esarath
